### Numpy Tutorials

NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

### What is an array

An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [5]:
## initially importing numpy

import numpy as np

In [6]:
my_lst = [1,2,3,4,5]

arr = np.array(my_lst)

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr

array([1, 2, 3, 4, 5])

In [9]:
print(arr)

[1 2 3 4 5]


In [10]:
arr.shape

(5,)

In [12]:
my_lst1 = [1,2,3,4,5]
my_lst2 = [6,7,8,9,0]
my_lst3 = [3,2,1,4,5]

arr = np.array([my_lst1,my_lst2,my_lst3])

In [13]:
arr

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [3, 2, 1, 4, 5]])

In [14]:
arr.shape

(3, 5)

In [17]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 3, 2],
       [1, 4, 5]])

In [18]:
arr.shape

(3, 5)

### Indexing

Index in array starts with 0 and ends with n-1

In [20]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [21]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr[0]

1

In [23]:
arr[5]

6

In [25]:
my_lst1 = [1,2,3,4,5]
my_lst2 = [6,7,8,9,0]
my_lst3 = [3,2,1,4,5]

arr = np.array([my_lst1,my_lst2,my_lst3])

In [26]:
arr

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [3, 2, 1, 4, 5]])

In [27]:
arr[:,:]

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [3, 2, 1, 4, 5]])

In [28]:
arr[0:2,:]

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [29]:
arr[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [30]:
arr [1:,1:3]

array([[7, 8],
       [2, 1]])

In [36]:
arr=np.arange(0,15)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
arr=np.arange(0,15,step=3)

In [39]:
arr

array([ 0,  3,  6,  9, 12])

In [40]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [41]:
arr = np.array([1,2,3,4,5,6,7,8,9])

arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
## copy

arr[3:]=100

In [43]:
arr

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [44]:
arr1 = arr

In [45]:
arr1[3:]=300

arr1

array([  1,   2,   3, 300, 300, 300, 300, 300, 300])

In [46]:
arr

array([  1,   2,   3, 300, 300, 300, 300, 300, 300])

**Note : In the above example we can see when we assign value of one variable to another variable and we change the value of any one variable it is affecting the other variable as well. In python referencing is used to point the location of value. so when value is updated for one variable the other variable which is referencing the same value will be affected.

In [50]:
## To over come Referencing we use copy(). It creates another memory space to store the value

arr1=arr.copy()

In [51]:
print(arr)
arr1[3:]=500
print(arr1)

[  1   2   3 300 300 300 300 300 300]
[  1   2   3 500 500 500 500 500 500]


In [52]:
### useful conditions in exploratory data analysis

arr

array([  1,   2,   3, 300, 300, 300, 300, 300, 300])

In [53]:
val = 2

arr < val

array([ True, False, False, False, False, False, False, False, False])

In [54]:
arr * 2

array([  2,   4,   6, 600, 600, 600, 600, 600, 600])

In [55]:
arr[arr<300]

array([1, 2, 3])

In [61]:
arr * arr1

array([     1,      4,      9, 150000, 150000, 150000, 150000, 150000,
       150000])

In [57]:
## create array and reshape

np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [58]:
np.ones(4)

array([1., 1., 1., 1.])

In [60]:
np.ones((2,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [67]:
## random distribution, Random values in a given shape.

np.random.rand(3,3)

array([[0.11118531, 0.23218017, 0.13853978],
       [0.22815226, 0.65748177, 0.84017419],
       [0.91538314, 0.50963362, 0.5941544 ]])

In [68]:
## Return a sample (or samples) from the "standard normal" distribution.

np.random.randn(3,3)

array([[-0.49965037,  0.60047733, -0.14077486],
       [-1.04494604,  1.58003819, -0.74136914],
       [-1.63317881, -1.22537448, -0.44544517]])

In [70]:
## Return random integers from `low` (inclusive) to `high` (exclusive).

np.random.randint(0,100,8)

array([45, 56, 28, 12, 60,  5, 88,  5])

In [71]:
np.random.randint(0,100,8).reshape(4,2)

array([[88, 31],
       [29, 12],
       [40, 79],
       [81, 22]])